#!/usr/bin/env node
/**
 * theme-build - generate every theme artifact from design/tokens.json.
 *
 * WHY THIS EXISTS
 *   A colour that lives in two places has two values. Application code never sees a hex
 *   literal; it sees a CSS custom property or a typed token whose value was generated here.
 *   Re-branding an application is then an edit to ONE file plus a rebuild.
 *
 * OUTPUTS (generated - never hand-edit, they are overwritten)
 *   <out>/tokens.generated.css   CSS custom properties for :root, [data-theme] and
 *                                prefers-color-scheme, plus non-colour scales.
 *   <out>/tokens.generated.ts    Typed token names + a runtime map, for code that needs a
 *                                value in JS (canvas, charts, meta theme-color, native).
 *
 * USAGE  node scripts/theme-build.mjs [--tokens <path>] [--out <dir>] [--check]
 *        --check  regenerate in memory and exit 2 if the committed files differ, so a
 *                 hand-edited generated file cannot ship.
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { appPath } from './lib/layout.mjs';

const argv = process.argv.slice(2);
const arg = (name, dflt) => {
  const i = argv.indexOf(name);
  return i >= 0 && argv[i + 1] ? argv[i + 1] : dflt;
};
const CHECK = argv.includes('--check');
const ROOT = process.cwd();
const TOKENS = path.resolve(ROOT, arg('--tokens', appPath(ROOT, 'design/tokens.json')));
const OUT = path.resolve(ROOT, arg('--out', appPath(ROOT, 'src/theme')));

/** Generated files are committed and checked byte-for-byte, so any path baked into them
 *  must read the same on every platform - never Windows backslashes. */
const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');

const tokens = JSON.parse(fs.readFileSync(TOKENS, 'utf8'));
const THEMES = ['light', 'dark'];
const kebab = (s) => s.replace(/\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const cssVar = (key) => '--' + kebab(key);

const semantic = Object.entries(tokens.semantic).filter(([k]) => !k.startsWith('_'));
const elevation = Object.entries(tokens.elevation ?? {});
const flatScales = {
  radius: tokens.radius ?? {},
  spacing: tokens.spacing ?? {},
  'font-size': tokens.typography?.size ?? {},
  'line-height': tokens.typography?.lineHeight ?? {},
  'font-weight': tokens.typography?.weight ?? {},
  duration: tokens.motion?.duration ?? {},
  easing: tokens.motion?.easing ?? {},
  layout: tokens.layout ?? {},
};

const themeBlock = (theme, indent = '  ') =>
  [
    ...semantic.map(([k, val]) => `${indent}${cssVar(k)}: ${val[theme]};`),
    ...elevation.map(([k, val]) => `${indent}${cssVar('shadow.' + k)}: ${val[theme]};`),
  ].join('\n');

const staticBlock = () =>
  Object.entries(flatScales)
    .flatMap(([group, map]) =>
      Object.entries(map)
        .filter(([, val]) => typeof val === 'string')
        .map(([k, val]) => `  --${group}-${kebab(k)}: ${val};`)
    )
    .join('\n');

/* Three-state theming, and the ORDER is the contract:
 *   :root                        LIGHT is always fully defined. A token defined only inside a
 *                                media query has no value when that query is false.
 *   @media dark + :not([data-theme='light'])   system preference wins when no explicit choice.
 *   :root[data-theme='dark'|'light']           an explicit choice beats the system, both ways.
 */
const css = `/* GENERATED by scripts/theme-build.mjs from ${rel(TOKENS)} - DO NOT EDIT. */
/* Rebuild: npm run theme:build    Verify: npm run theme:contrast */

:root {
  color-scheme: light dark;

${staticBlock()}

  /* --- LIGHT (default, always fully defined) --- */
${themeBlock('light')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${themeBlock('dark', '    ')}
  }
}

:root[data-theme='dark'] {
${themeBlock('dark')}
}

:root[data-theme='light'] {
${themeBlock('light')}
}

html, body {
  background: var(--background);
  color: var(--text-body);
  font-family: ${tokens.typography.fontFamilyBase};
}

/* Focus is never removed - only restyled. */
:focus-visible {
  outline: 2px solid var(--border-focus);
  outline-offset: 2px;
}

/* Motion collapses to its END STATE; it is never cancelled mid-transition. */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 1ms !important;
    scroll-behavior: auto !important;
  }
}

/* Theme-aware assets: one markup block, correct artwork per theme, no JS, no flash. */
[data-asset-theme='dark']  { display: none; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) [data-asset-theme='light'] { display: none; }
  :root:not([data-theme='light']) [data-asset-theme='dark']  { display: initial; }
}
:root[data-theme='dark']  [data-asset-theme='light'] { display: none; }
:root[data-theme='dark']  [data-asset-theme='dark']  { display: initial; }
:root[data-theme='light'] [data-asset-theme='light'] { display: initial; }
:root[data-theme='light'] [data-asset-theme='dark']  { display: none; }
`;

const ts = `/* GENERATED by scripts/theme-build.mjs from ${rel(TOKENS)} - DO NOT EDIT. */
/* Rebuild: npm run theme:build */

/** Every semantic colour role in the design system. */
export const semanticTokens = [
${semantic.map(([k]) => `  '${k}',`).join('\n')}
] as const;
export type SemanticToken = (typeof semanticTokens)[number];

/** CSS custom-property name for a token. */
export const cssVarFor = (t: SemanticToken): string =>
  '--' + t.replace(/\\./g, '-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/** \`var(--x)\` reference, for style props and CSS-in-JS. Prefer this in the DOM. */
export const v = (t: SemanticToken): string => \`var(\${cssVarFor(t)})\`;

/** Resolved values per theme. Use ONLY where a real value is required (canvas, charts,
 *  \`<meta name="theme-color">\`, native platforms). */
export const themeValues = {
${THEMES.map(
  (t) => `  ${t}: {
${semantic.map(([k, val]) => `    '${k}': '${val[t]}',`).join('\n')}
  },`
).join('\n')}
} as const;

export type ThemeName = keyof typeof themeValues;

export const scales = {
  radius: ${JSON.stringify(tokens.radius)},
  spacing: ${JSON.stringify(tokens.spacing)},
  typography: ${JSON.stringify(tokens.typography)},
  motion: ${JSON.stringify(tokens.motion)},
  layout: ${JSON.stringify(tokens.layout)},
} as const;

/** Declared theme-aware assets, rendered by <ThemedImage />. */
export const themedAssets = ${JSON.stringify(
  Object.fromEntries(
    (tokens.assets?.items ?? []).map((a) => [a.id, { light: a.light, dark: a.dark, alt: a.description }])
  ),
  null,
  2
)} as const;
`;

const targets = [
  [path.join(OUT, 'tokens.generated.css'), css],
  [path.join(OUT, 'tokens.generated.ts'), ts],
];

let drift = 0;
for (const [file, content] of targets) {
  if (CHECK) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current !== content) {
      drift++;
      console.error(`DRIFT  ${rel(file)} does not match design/tokens.json.`);
    }
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content, 'utf8');
    console.log(`wrote  ${rel(file)}`);
  }
}

if (CHECK && drift) {
  console.error(`\nBLOCKED: ${drift} generated theme file(s) are stale or hand-edited.`);
  console.error('Fix: npm run theme:build   then commit the result.');
  process.exit(2);
}
if (CHECK) console.log('OK  theme artifacts are in sync with design/tokens.json');
